options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args: ['-c', 'pip install -r requirements.txt && pytest']
    dir: 'expense-tracker-api'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/expense-tracker-api', '.']
    dir: 'expense-tracker-api'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expense-tracker-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'expense-tracker-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/expense-tracker-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
